# fly.toml app configuration file generated for static-ancient-sky-3218 on 2024-08-30T16:24:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'static-ancient-sky-3218'
primary_region = 'lhr'

[build]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
